export default {
  login: "Barsheyr",
  id: 64050352,
  node_id: "MDQ6VXNlcjY0MDUwMzUy",
  avatar_url: "https://avatars.githubusercontent.com/u/64050352?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Barsheyr",
  html_url: "https://github.com/Barsheyr",
  followers_url: "https://api.github.com/users/Barsheyr/followers",
  following_url: "https://api.github.com/users/Barsheyr/following{/other_user}",
  gists_url: "https://api.github.com/users/Barsheyr/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Barsheyr/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Barsheyr/subscriptions",
  organizations_url: "https://api.github.com/users/Barsheyr/orgs",
  repos_url: "https://api.github.com/users/Barsheyr/repos",
  events_url: "https://api.github.com/users/Barsheyr/events{/privacy}",
  received_events_url: "https://api.github.com/users/Barsheyr/received_events",
  type: "User",
  site_admin: false,
  name: "Bashir Amokomowo",
  company: null,
  blog: "",
  location: null,
  email: null,
  hireable: null,
  bio: "Hi, A frontend Developer ready to work\r\n",
  twitter_username: "Barsheyr",
  public_repos: 70,
  public_gists: 0,
  followers: 3,
  following: 7,
  created_at: "2020-04-21T00:44:27Z",
  updated_at: "2023-10-31T22:30:18Z",
};
